const palette = {
  primary: "#16A34A",
  primaryDark: "#0B5D2A",
  primaryDeep: "#08361B",
  primaryLight: "#1F7A3D",
  accent: "#F59E0B",
  accentLight: "#FFF3CD",
  background: "#B8D4BE",
  backgroundSecondary: "#A3C5AA",
  card: "#FFFFFF",
  cardSecondary: "#E8F2EA",
  text: "#1A2E1A",
  textSecondary: "#4A6B4A",
  textMuted: "#7A9B7A",
  border: "#D4E4D4",
  borderLight: "#BED9BE",
  success: "#22C55E",
  successLight: "#D1FAE0",
  warning: "#F59E0B",
  warningLight: "#FFF3CD",
  danger: "#F87171",
  dangerLight: "#FEE2E2",
  info: "#38BDF8",
  infoLight: "#E0F2FE",
  overlay: "rgba(0, 0, 0, 0.55)",
  tabBar: "#9BBAA2",
  tabBarInactive: "#8BAA8B",
  tabInactiveBg: "rgba(22, 163, 74, 0.12)",
  tabInactiveBorder: "rgba(22, 163, 74, 0.25)",
  tabInactiveText: "#5A7A5A",
  tabGlow: "rgba(34, 197, 94, 0.15)",
  textInverse: "#FFFFFF",
};

export default {
  ...palette,
  bg: palette.background,
  light: {
    text: palette.text,
    background: palette.background,
    tint: palette.primary,
    tabIconDefault: palette.tabBarInactive,
    tabIconSelected: palette.primary,
  },
};
